# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- sisco-FFTHH

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js v10'

    # Restore depdencies, compile our Typescript, and run tests.
    - script: |
        yarn install
        yarn build
        yarn test
      displayName: 'Restore, build and test'
    
    # Publish test results.
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'spec/TestResults.xml' 
        failTaskOnFailedTests: true

    - task: FileTransform@1
      displayName: 'Updating Appsetings.json'
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/'
        fileType: 'json'
        targetFiles: 'appsettings.json'

    - task: CmdLine@2
      displayName: 'Update app_version in .env file'
      inputs:
        script: |
            echo Displaying build folder contents
            ls -a
            echo 
            echo viewing contents of appsectings.json
            cat appsettings.json
            echo 
            echo Copy appsettings.json to ./dist folder
            echo  
            cp appsettings.json '$(System.DefaultWorkingDirectory)/dist/appsettings.json'
            echo Displaying dist folder contents 
            cd dist
            ls -r

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
